# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-job:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run:
          name: Run Tests
          command: yarn run test:coverage
      - run:
          name: Build Tests Types
          command: yarn run test:types

  deploy-docs:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Build Docs
          command: yarn run docs
      - run:
          name: Deploy Docs to Zeit
          command: yarn run docs:deploy

  publish-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Publish Package
          command: cd dist && yarn run semantic-release

workflows:
  version: 2
  test:
    jobs:
      - test-job
      - publish-job:
          requires:
            - test-job
          filters:
            branches:
              only:
                - next
                - master
      - deploy-docs:
          requires:
            - publish-job
          filters:
            branches:
              only:
                - master
